config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :destroy, :new, :index]
  resources :sessions, only: [:create, :destroy, :new]

  resources :bands

  resources :albums, except: [:index]

  resources :tracks, except: [:index]

end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :band

  has_many :tracks
end

app/models/band.rb
class Band < ActiveRecord::Base
  has_many :albums

  has_many :tracks,
    through: :albums,
    source: :tracks


  validates :name, presence: true, uniqueness: true

end

app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :album

  has_one :band,
    through: :album,
    source: :band
end

app/models/user.rb
class User < ActiveRecord::Base

  attr_reader :password
  after_initialize :ensure_session_token

  validates :email, :session_token, :password_digest, presence: true
  validates :email, :session_token, uniqueness: true
  validates :password, length: {minimum: 8, allow_nil: true}

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def self.find_by_credentials(email, password)
    found_user = User.find_by(email: email)
    return nil unless found_user
    if found_user.is_password?(password)
      found_user
    else
      nil
    end
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def password=(password)
    @pasword = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def logged_in?
    
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def create
    album_params
    @album = Album.new(album_params)

    if @album.save
      redirect_to bands_url
    else
      flash.now[:album_errors] = @album.errors.full_messages
      render :new
    end
  end

  def new
    render :new
  end

  private
  def album_params
    first_params = params.require(:album).permit(:name, :band, :recording_style)
    band_id = Band.find_by(name: first_params[:name])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception

  def current_user
    User.find_by(session_token: session[:session_token])
  end

  def login(user)
    session[:session_token] = user.session_token
  end

  def login!(user)
    user.reset_session_token
    session[:session_token] = user.session_token
  end

  def logout
    current_user.reset_session_token
  end

  def logged_in?(user)
    user == current_user
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    render :index
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to bands_url
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def new
    render :new
  end

  def edit

  end

  def show

  end

  def update

  end

  def destroy

  end

  private

  def band_params
    params.require(:band).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(user_params[:email], user_params[:pasword])
    if @user
      @user.reset_session_token!
      login(@user)
      redirect_to users_url
    else
      flash.now[:errors] = "Bad login credentials"
      render :new
    end
  end

  def destroy
    logout
  end

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    render :index
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login(@user)
      redirect_to users_url
    else
      flash.now[:user_errors] = @user.errors.full_messages
      render :new
    end
  end

  def new#aka show me the webpage that lets me input info about new users
    render :new
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/albums/new.html.erb
<form  action="<%= albums_url %>" method="post">

  <label>Band:
    <select class="" name="album[band]">
      <% Band.all.each do |band| %>
      <option value="<% band.name %>"><%= band.name %></option>
      <% end %>
    </select>
  </label>

  <label>Album Name:
    <input type="text" name="album[name]" value="">
  </label>

  <label>
    <select name="album[recording_style]">
      <option value="live">Live</option>
      <option value="studio">Studio</option>
    </select>
  </label>

  <input type="submit" value="Submit Album">

</form>

app/views/bands/index.html.erb
<h1>Bands in my bandass database</h1>

<ul>
  <% Band.all.each do |band| %>
  <li> <%= band.name %></li>
  <% end %>
</ul>

app/views/bands/new.html.erb
<form  action="<%= bands_url %>" method="post">

  <label>Band Name:
    <input type="text" name="band[name]" value="">
  </label>

  <input type="submit" value="Submit Band">

</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<br>
<br>
<br>
<footer>
  Errors:
  <%= flash[:errors] %>
</footer>


</body>
</html>

app/views/partials/_bandsform.html.erb
<!-- <% button_value = case action
  when users_url
    "Create New User"
  when sessions_url
    "Log in"
  end
%> -->
<!-- <form  action="bands_url" method="post">

  <label>Band Name:
    <input type="text" name="band[name]" value="">
  </label>

  <input type="submit" value=" <%= button_value %>">

</form> -->

app/views/partials/_form.html.erb
<% button_value = case action
  when users_url
    "Create New User"
  when sessions_url
    "Log in"
  end
%>

<form  action="<%= action %>" method="post">

  <label>Username:
    <input type="text" name="user[email]" value="">
  </label>

  <label>Password:
    <input type="password" name="user[password]" value="">
  </label>

  <input type="submit" value=" <%= button_value %>">

</form>

app/views/partials/_usersform.html.erb
<% button_value = case action
  when users_url
    "Create New User"
  when sessions_url
    "Log in"
  end
%>

<form  action="<%= action %>" method="post">

  <label>Username:
    <input type="text" name="user[email]" value="">
  </label>

  <label>Password:
    <input type="password" name="user[password]" value="">
  </label>

  <input type="submit" value=" <%= button_value %>">

</form>

app/views/users/index.html.erb
<h1>Yo this is the Index page</h1>
<p>
  <% User.all.each do |user| %>
  <%= user.email %>
  <%= "logged in" if user.session_token == session[:session_token] %>
  <br>
  <br>
  <% end %>
</p>

app/views/users/new.html.erb
<h1>This is the new user form from app/views/users</h1>

<%= render "./partials/usersform", action: users_url %>

<!-- <form class="" action="<%= users_url %>" method="post">

  <label>Username:
    <input type="text" name="user[email]" value="">
  </label>

  <label>Password:
    <input type="password" name="user[password]" value="">
  </label>

  <input type="submit" value="Create New User!!!">

</form> -->